apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalog-data
  namespace: caramel-store
  labels:
    app.kubernetes.io/part-of: caramel-vanilla
    app.kubernetes.io/component: store
    app.kubernetes.io/name: caramel-store
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: rook-ceph-block
