apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: caramel-store
  namespace: caramel-store
  labels:
    app.kubernetes.io/part-of: caramel-vanilla
    app.kubernetes.io/component: store
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: caramel-store
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
